<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="EGCA1-0091" failures="1" tests="1" name="XYZ_Bank" time="4.396" errors="0" timestamp="2023-06-25T22:57:14 EET">
  <testcase classname="testNGDataProvider.TestNGDataProvider" name="test3" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at pages.PageBase.readExcelData(PageBase.java:194)
at testNGDataProvider.TestNGDataProvider.getData3(TestNGDataProvider.java:24)
... 24 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="testNGDataProvider.TestNGDataProvider" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="testNGDataProvider.TestNGDataProvider" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- XYZ_Bank -->
